//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public Nullable<int> product { get; set; }
        public Nullable<int> user { get; set; }
        public Nullable<int> Qte { get; set; }
        public Nullable<System.DateTime> createdAT { get; set; }
    
        public virtual product product1 { get; set; }
        public virtual user user1 { get; set; }
    }
}
