//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public Nullable<int> customer { get; set; }
        public Nullable<int> payment { get; set; }
        public string orderDetails { get; set; }
        public Nullable<System.DateTime> createdAT { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual user user { get; set; }
        public virtual payment payment1 { get; set; }
    }
}
